record_col_types = {
        'covid19_emis_gp_clinical': {
            'eid': 'Int64',
            'event_dt': 'str',
            'code_type': 'str',
            'code': 'str',
            'value': 'str',
            'unit':'str' 
        },
        'covid19_emis_gp_scripts': {
            'eid': 'Int64',
            'issue_date': 'str',
            'code_type': 'str',
            'code': 'str'
        },
        'covid19_misc': {
            'eid': 'Int64',
            'blood_group': 'str'
        },
        'covid19_result': {
            'eid': 'Int64',
            'specdate': 'str',
            'spectype': 'Int64',
            'laboratory': 'Int64',
            'origin': 'Int64',
            'result': 'Int64',
            'acute': 'Int64',
            'hosaq': 'Int64',
            'reqorg': 'Int64'
        },
        'covid19_tpp_gp_clinical': {
            'eid': 'Int64',
            'event_dt': 'str',
            'code_type': 'Int64',
            'code': 'str',
            'value': 'float64'
        },
        'covid19_tpp_gp_scripts': {
            'eid': 'Int64',
            'issue_date': 'str',
            'dmd_code': 'str'
        },
        'death_cause': {
            'eid': 'Int64',
            'ins_index': 'Int64',
            'arr_index': 'Int64',
            'level': 'Int64',
            'cause_icd10': 'str'
        },
        'death': {
            'eid': 'Int64',
            'ins_index': 'Int64',
            'dsource': 'str',
            'source': 'Int64',
            'date_of_death': 'str'
        },
        'gp_clinical': {
            'eid': 'Int64',
            'data_provider': 'Int64',
            'event_dt': 'str',
            'read_2': 'str',
            'read_3': 'str',
            'value1': 'object',
            'value2': 'str',
            'value3': 'str'
        },
        'gp_registrations': {
            'eid': 'Int64',
            'data_provider': 'Int64',
            'reg_date': 'str',
            'deduct_date': 'str'
        },
        'gp_scripts': {
            'eid': 'Int64',
            'data_provider': 'Int64',
            'issue_date': 'str',
            'read_2': 'str',
            'bnf_code': 'str',
            'dmd_code': 'Int64',
            'drug_name': 'str',
            'quantity': 'str'
        },
        'hesin_critical': {
            'eid': 'Int64',
            'ins_index': 'Int64',
            'arr_index': 'Int64',
            'dsource': 'str',
            'source': 'Int64',
            'ccstartdate': 'str',
            'ccadmitype': 'Int64',
            'ccadmisorc': 'Int64',
            'ccsorcloc': 'Int64',
            'ccdisdate': 'str',
            'ccdisrdydate': 'str',
            'ccdisstat': 'Int64',
            'ccdisdest': 'Int64',
            'ccdisloc': 'Int64',
            'ccapcrel': 'Int64',
            'bressupdays': 'Int64',
            'aressupdays': 'Int64',
            'bcardsupdays': 'Int64',
            'acardsupdays': 'Int64',
            'rensupdays': 'Int64',
            'neurosupdays': 'Int64',
            'gisupdays': 'Int64',
            'dermsupdays': 'Int64',
            'liversupdays': 'Int64',
            'orgsupmax': 'Int64',
            'cclev2days': 'Int64',
            'cclev3days': 'Int64',
            'ccunitfun': 'Int64',
            'unitbedconfig': 'Int64'
        },
        'hesin_delivery': {
            'eid': 'Int64',
            'ins_index': 'Int64',
            'arr_index': 'Int64',
            'gestat': 'Int64',
            'delplac': 'Int64',
            'delmeth': 'str',
            'birordr': 'str',
            'birstat': 'Int64',
            'biresus': 'Int64',
            'sexbaby': 'Int64',
            'birweight': 'Int64',
            'delstat': 'Int64'
        },
        'hesin_diag': {
            'eid': 'Int64',
            'ins_index': 'Int64',
            'arr_index': 'Int64',
            'level': 'Int64',
            'diag_icd9': 'str',
            'diag_icd9_nb': 'str',
            'diag_icd10': 'str',
            'diag_icd10_nb': 'str'
        },
        'hesin_maternity': {
            'eid': 'Int64',
            'ins_index': 'Int64',
            'numbaby': 'Int64',
            'numpreg': 'Int64',
            'anasdate': 'str',
            'anagest': 'Int64',
            'antedur': 'Int64',
            'delinten': 'Int64',
            'delchang': 'Int64',
            'delprean': 'Int64',
            'delposan': 'Int64',
            'delonset': 'Int64',
            'postdur': 'Int64',
            'matage': 'Int64'
        },
        'hesin_oper': {
            'eid': 'Int64',
            'ins_index': 'Int64',
            'arr_index': 'Int64',
            'level': 'Int64',
            'opdate': 'str',
            'oper3': 'str',
            'oper3_nb': 'str',
            'oper4': 'str',
            'oper4_nb': 'str',
            'posopdur': 'Int64',
            'preopdur': 'Int64'
        },
        'hesin_psych': {
            'eid': 'Int64',
            'ins_index': 'Int64',
            'detncat': 'object',
            'detndate': 'str',
            'mentcat': 'Int64',
            'admistat': 'Int64',
            'leglstat': 'Int64'
        },
        'hesin': {
            'eid': 'Int64',
            'ins_index': 'Int64',
            'dsource': 'str',
            'source': 'Int64',
            'epistart': 'str',
            'epiend': 'str',
            'epidur': 'Int64',
            'bedyear': 'Int64',
            'epistat': 'Int64',
            'epitype': 'Int64',
            'epiorder': 'Int64',
            'spell_index': 'Int64',
            'spell_seq': 'Int64',
            'spelbgin': 'Int64',
            'spelend': 'str',
            'speldur': 'Int64',
            'pctcode': 'str',
            'gpprpct': 'str',
            'category': 'Int64',
            'elecdate': 'str',
            'elecdur':'Int64',
            'admidate': 'str',
            'admimeth_uni': 'Int64',
            'admimeth': 'str',
            'admisorc_uni': 'object',
            'admisorc': 'str',
            'firstreg': 'Int64',
            'classpat_uni': 'object',
            'classpat': 'str',
            'intmanag_uni': 'Int64',
            'intmanag': 'Int64',
            'mainspef_uni': 'Int64',
            'mainspef': 'str',
            'tretspef_uni': 'Int64',
            'tretspef': 'str',
            'operstat': 'Int64',
            'disdate': 'str',
            'dismeth_uni': 'Int64',
            'dismeth': 'Int64',
            'disdest_uni': 'object',
            'disdest': 'str',
            'carersi': 'Int64'
        }
    }